// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi-_bREc7EYVelc1T5xB3mOIs32nw4Zgc',
    appId: '1:803682927970:web:713cb4e8a9a4e86c79983b',
    messagingSenderId: '803682927970',
    projectId: 'fasum-app-dd0c1',
    authDomain: 'fasum-app-dd0c1.firebaseapp.com',
    storageBucket: 'fasum-app-dd0c1.appspot.com',
    measurementId: 'G-D2FRVBRZ9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv2RmWrqPYcBe1lH6gCoPYa0Y0kGBb6GM',
    appId: '1:803682927970:android:c56e5ac883451d8379983b',
    messagingSenderId: '803682927970',
    projectId: 'fasum-app-dd0c1',
    storageBucket: 'fasum-app-dd0c1.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnDlhY4tR2C1bMhN4tUrVNEGVBA6xcD4w',
    appId: '1:803682927970:ios:1cdb17634209f64379983b',
    messagingSenderId: '803682927970',
    projectId: 'fasum-app-dd0c1',
    storageBucket: 'fasum-app-dd0c1.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnDlhY4tR2C1bMhN4tUrVNEGVBA6xcD4w',
    appId: '1:803682927970:ios:1cdb17634209f64379983b',
    messagingSenderId: '803682927970',
    projectId: 'fasum-app-dd0c1',
    storageBucket: 'fasum-app-dd0c1.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi-_bREc7EYVelc1T5xB3mOIs32nw4Zgc',
    appId: '1:803682927970:web:02137c6ad34ba5b479983b',
    messagingSenderId: '803682927970',
    projectId: 'fasum-app-dd0c1',
    authDomain: 'fasum-app-dd0c1.firebaseapp.com',
    storageBucket: 'fasum-app-dd0c1.appspot.com',
    measurementId: 'G-Q7YKQ3BPNX',
  );

}